openapi: 3.0.0
info:
  title: Blog API
  version: 1.0.0
servers:
  - url: 'http://localhost:3001/api/v1'
    description: blog server
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: 123456
                fullName:
                  type: string
                  example: Test User
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  messageKey:
                    type: string
                    example: user.created.success
                  message:
                    type: string
                    example: User created successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: cuid123
                      email:
                        type: string
                        example: test@example.com
                      fullName:
                        type: string
                        example: Test User
        '400':
          description: Validation failed
        '409':
          description: Email already exists
components:
  schemas: null
