openapi: 3.0.0
info:
  title: Blog API
  version: "1.0.0"
  description: API Documentation for Blog Platform
servers:
  - url: http://localhost:3001/api/v1
    description: Local Development
  - url: http://blog-api.lamphamit.site:3000/api/v1
    description: Production Server

paths:
  # Auth Module
  /auth/register:
    $ref: "./modules/auth.yaml#/paths/~1auth~1register"
  /auth/login:
    $ref: "./modules/auth.yaml#/paths/~1auth~1login"
  /auth/me:
    $ref: "./modules/auth.yaml#/paths/~1auth~1me"

  # Post Module
  /posts:
    $ref: "./modules/post.yaml#/paths/~1posts"

  /posts/{slug}:
    $ref: "./modules/post.yaml#/paths/~1posts~1{slug}"
  /posts/{id}/upvote:
    $ref: "./modules/post.yaml#/paths/~1posts~1{id}~1upvote"

  /upload/image:
    $ref: "./modules/upload.yaml#/paths/~1upload~1image"

  # Series Module
  /series:
    $ref: "./modules/series.yaml#/paths/~1series"
  /series/{slug}:
    $ref: "./modules/series.yaml#/paths/~1series~1{slug}"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT