name: Deploy Blog Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Generate .env for deploy
        env:
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: |          
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries | .[] | select(.key | startswith("PROD_")) | "\(.key | sub("^PROD_"; ""))=\(.value)"' >> .env.deploy

      - name: Copy .env to VPS
        run: |
          scp -o StrictHostKeyChecking=no .env.deploy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/blog/.env.production

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /var/www/blog
            git fetch origin
            git pull origin main
            npm install
            npm run build
            
            npx swagger-cli bundle docs/openapi.yaml -o docs/bundled.yaml --type yaml
            
            npm run migrate:prod
            npx prisma generate
            pm2 reload ecosystem.config.js --env production
          "